PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX do178c: <https://gitlab.dlr.de/ft-ssy-avs/ap/coua/ontologies/do178c#>
PREFIX coua: <https://gitlab.dlr.de/ft-ssy-avs/ap/coua/schema#>

SELECT ?element ?desc
WHERE
{
	?c a do178c:SoftwareRequirementsData .
	?reqs a ?c .
	?reqs rdf:rest*/rdf:first ?element .
	?element coua:description ?desc .
}
ORDER BY ?element
