stages:
  - check
  - test
  - cert

default:
  tags: [nix]
  before_script:
    - git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.dlr.de/".insteadOf "https://gitlab.dlr.de/"
    - mkdir -p ~/.config/nix
    - echo 'accept-flake-config = true' >> ~/.config/nix/nix.conf

check-formatting:
  stage: check
  script:
    - nix fmt -- --fail-on-change --no-cache

commit-check:
  stage: check
  script:
    - nix develop --command cog check

mypy:
  stage: check
  script:
    - nix develop --command mypy coua

coua-cert:
  variables:
    COUA_STORE: "db"
    COUA_JUNIT_XML: ""
    COUA_CARGO_REQUIREMENTS: ""
  stage: cert
  script: |
    nix build .#
    ./result/bin/coua-conv-junit $COUA_JUNIT_XML doc/source/junit.ttl
    ./result/bin/coua-conv-cargo-requirements $COUA_CARGO_REQUIREMENTS doc/source/cargo-requirements.ttl
    ./result/bin/coua-check-do178c doc/source/*.ttl
    cd doc
    nix develop --command make html
  artifacts:
    paths:
      [doc/build/html]
