stages:
  - check
  - test
  - cert
  - deploy

default:
  tags: [nix]
  before_script:
    - git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.dlr.de/".insteadOf "https://gitlab.dlr.de/"
    - mkdir -p ~/.config/nix
    - echo 'accept-flake-config = true' >> ~/.config/nix/nix.conf

check-formatting:
  stage: check
  script:
    - nix fmt -- --fail-on-change --no-cache

commit-check:
  stage: check
  script:
    - nix develop --command cog check

mypy:
  stage: check
  script:
    - nix develop --command mypy coua

test:
  stage: test
  script:
    - nix develop --command pytest --junit-xml=junit.xml --cov=coua --cov-report term --cov-report xml:coverage.xml
  artifacts:
    paths:
      [junit.xml]
    reports:
      junit: junit.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

coua-cert:
  dependencies:
    - test
  variables:
    COUA_STORE: "db"
    COUA_CARGO_REQUIREMENTS: ""
  stage: cert
  script:
    - cd doc && nix develop --command make html
  artifacts:
    paths:
      [doc/build/html]

pages:
  stage: deploy
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  needs: [coua-cert]
  script:
    - mv doc/build/html public
  artifacts:
    paths: [public]
