default:
  tags: [nix]
  before_script:
    - git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.dlr.de/".insteadOf "ssh://git@gitlab.dlr.de"
    - mkdir -p ~/.config/nix
    - echo 'accept-flake-config = true' >> ~/.config/nix/nix.conf

formatting:
  script:
    - nix fmt -- --fail-on-change --no-cache

commit-check:
  script:
    - nix develop --command cog check

rust-tests:
  script:
    - ./ci/rust-tests.sh
  artifacts:
    paths:
      [clippy-lints.json, code-quality-report.json, target/doc]
    reports:
      codequality: code-quality-report.json
      junit: junit-*.xml

rust-coverage:
  script:
    - ./ci/rust-coverage.sh
  artifacts:
    paths: [coverage-lcov.dat, target/llvm-cov/html]
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage-cobertura.xml

coua-cert:
  script:
    - nix develop --command cargo-requirements --format ttl --testns "http://coua" --reqns "http://coua"
    - nix develop --command cargo run -p coua -- -o report -s ontologies/do178c resources/*
  artifacts:
    paths:
      [report]
