stages:
  - check
  - test
  - cert

default:
  tags: [nix]
  before_script:
    - git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.dlr.de/".insteadOf "ssh://git@gitlab.dlr.de"
    - mkdir -p ~/.config/nix
    - echo 'accept-flake-config = true' >> ~/.config/nix/nix.conf

formatting:
  stage: check
  script:
    - nix fmt -- --fail-on-change --no-cache

commit-check:
  stage: check
  script:
    - nix develop --command cog check

rust-tests:
  stage: test
  script:
    - ./ci/rust-tests.sh
  artifacts:
    paths:
      [clippy-lints.json, code-quality-report.json, target/doc, junit-*.xml]
    reports:
      codequality: code-quality-report.json
      junit: junit-*.xml

rust-coverage:
  stage: test
  script:
    - ./ci/rust-coverage.sh
  artifacts:
    paths: [coverage-lcov.dat, target/llvm-cov/html]
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage-cobertura.xml

coua-cert:
  stage: cert
  dependencies: [ rust-tests, rust-coverage ]
  script:
    - nix develop --command ./ci/coua-cert.sh
  artifacts:
    paths:
      [report]
