stages:
  - check
  - test
  - cert
  - deploy

default:
  tags: [nix]
  before_script:
    - git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.dlr.de/".insteadOf "https://gitlab.dlr.de/"
    - git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.dlr.de/".insteadOf "ssh://git@gitlab.dlr.de/"
    - mkdir -p ~/.config/nix
    - echo 'accept-flake-config = true' >> ~/.config/nix/nix.conf

check-formatting:
  stage: check
  script:
    - nix develop --command make check-format

commit-check:
  stage: check
  script:
    - nix develop --command make commit-check

mypy:
  stage: check
  script:
    - nix develop --command make mypy

test:
  stage: test
  script:
    - nix develop --command make test
  artifacts:
    paths:
      [junit.xml]
    reports:
      junit: junit.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

doc:
  dependencies:
    - test
  stage: cert
  script:
    - nix develop --command make cert
  artifacts:
    paths:
      [doc/build/html, doc/source/imported.nt]

cert:
  dependencies:
    - test
  stage: cert
  script:
    - nix develop --command make cert

pages:
  stage: deploy
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  needs: [doc]
  script:
    - mv doc/build/html public
  artifacts:
    paths: [public]
