name = "Coua"
checks = ["do178c", "coua"]

[do178c]
software = "https://dlr.de/ft/ssy/coua"
software_level = "A"

[artifacts.Junit.morph]
file_path = "junit.xml"

[artifacts.Cobertura.morph]
file_path = "coverage.xml"
mappings = "coua/mappings/cobertura.ttl"

[artifacts."traces.json"]
type = "malkoha"
