[project]
name = "Coua"

[checks]
suites = ["do178c", "coua"]
disabled = [
  # URIs of disabled checks, they will run, but their result will not be counted as a failure
  "https://gitlab.dlr.de/ft-ssy-avs/ap/coua/ontologies/do178c#Obj_A_5_1"
]

[do178c]
software = "https://dlr.de/ft/ssy/coua"
software_level = "A"

[artifacts.Junit.morph]
file_path = "junit.xml"

[artifacts.Cobertura.morph]
file_path = "coverage.xml"
mappings = "coua/mappings/cobertura.ttl"

[artifacts."traces.json"]
type = "malkoha"
