checks = ["do178c", "coua"]

[artifacts.Junit.morph]
file_path = "junit.xml"

[artifacts.Cobertura.morph]
file_path = "coverage.xml"
mappings = "coua/mappings/cobertura.ttl"

[artifacts.Traces.morph]
file_path = "traces.json"
mappings = "coua/mappings/traces.ttl"
