[project]
name = "Coua"

[checks]
suites = ["do178c", "coua", "cobertura"]
disabled = [
  # URIs of disabled checks, they will run, but their result will not be counted as a failure
  "https://raw.githubusercontent.com/cobertura/web/master/htdocs/xml/coverage-04.dtd#check_all_lines_covered"
]

[do178c]
software = "https://dlr.de/ft/ssy/coua"
software_level = "A"

[artifacts.Junit.morph]
file_path = "junit.xml"

[artifacts."coverage.xml"]
type = "cobertura"

[artifacts."traces.json"]
type = "malkoha"
