[Req01]
description = "The certification framework shall provide a library of functions for ingesting artifacts produced by COTS tools."
owner = "DLR"
level = "system"
use-cases = [ "UC04" ]

[Req02]
description = "The framework shall provide means for describing the interfaces, inputs and outputs of custom COTS tools."
owner = "DLR"
level = "functional"
use-cases = [ "UC04" ]
trace = "Req01"

[Req03]
description = "Coua shall generate a certification report which includes all certification objectives and references to all required evidences it has access to."
owner = "DLR"
level = "functional"
trace = "Req12"
use-cases = [ "UC01" ]

[Req04]
description = "While CI is in use, when changes are committed to the SCM, Coua shall generate a certification report."
owner = "DLR"
level = "functional"
trace = "Req12"
use-cases = [ "UC02" ]

[Req05]
description = "Coua shall be able to ingest requirements, evidences, justifications and data-items from artifacts produced by COTS tools."
owner = "DLR"
level = "functional"
trace = "Req01"
use-cases = [ "UC04" ]

[Req06]
description = "Coua shall provide means to specify how to obtain artifacts created by other tools."
owner = "DLR"
level = "functional"
trace = "Req01"
use-cases = ["UC06"]

[Req07]
description = "When the certification report is generated, Coua shall always produce the same report for the same project state."
owner = "DLR"
level = "functional"
trace = "Req12"
use-cases = ["UC05"]

[Req08]
description = "Coua shall provide means to extend the ontologies of generalized standards such as DO-178C to project-specific certification objectives"
owner = "DLR"
level = "functional"
trace = "Req50"
use-cases = ["UC6"]

[Req9]
description = "Coua shall provide means to identify which ontologies were used to perform verification and validation in the certification report."
owner = "DLR"
level = "functional"
trace = "Req11"
use-cases = ["UC6"]

[Req10]
description = "Coua shall track the association between artifacts like requirements, test cases, source code and object code (tracing)."
owner = "DLR"
level = "functional"
trace = "Req11"
use-cases = ["UC8"]

[Req11]
description = "Coua shall track the association between artifacts and objectives."
owner = "DLR"
level = "system"
use-cases = ["UC08"]

[Req12]
description = "Coua shall generate certification reports."
owner = "DLR"
level = "system"
use-cases = ["UC01"]

[Req13]
description = "While Coua performs validation activities, if any failing satisfiable objectives are encountered, Coua shall indicate to the CI that its activities have failed."
owner = "DLR"
level = "functional"
use-cases = ["UC10"]
trace = "Req50"

[Req14]
description = "While Coua performs validation activities, if any failing unsatisfiable objectives are encountered, Coua shall not indicate that its activities have failed. "
owner = "DLR"
level = "functional"
use-cases = ["UC10"]
trace = "Req50"

[Req15]
description = "Coua shall provide a way to mark objectives as unsatisfiable"
owner = "DLR"
level = "functional"
use-cases = ["UC10"]
trace = "Req50"

[Req16]
description = "Coua shall provide a way to remove the unsatisfiable mark from objectives."
owner = "DLR"
level = "functional"
use-cases = ["UC10"]
trace = "Req50"

[Req17]
description = "While CI is in use, Coua shall signal failed objectives as errors"
owner = "DLR"
level = "non-functional"
use-cases = ["UC02"]
trace = "Req20"

[Req18]
description = "Coua shall ingest artifacts in the Static Analysis Results Interchange Format (SARIF) format without additional processing"
owner = "DLR"
level = "functional"
use-cases = ["UC07"]
trace = "Req01"

[Req19]
description = "Coua shall be executable independently of CI, e.g. locally on a developer’s or tester’s computer"
owner = "DLR"
level = "functional"
use-cases = ["UC05"]
trace = "Req20"

[Req20]
description = "Coua shall be executable in CI"
owner = "DLR"
level = "system"
use-cases = ["UC02"]

[Req21]
description = "Coua shall provide means for ingesting artifacts from the local filesystem"
owner = "DLR"
level = "functional"
use-cases = ["UC03"]
trace = "Req01"

[Req22]
description = "When Coua produces a certification report, where data from artifacts is used, Coua shall include data about the tools that produced the artifacts."
owner = "DLR"
level = "functional"
use-cases = ["UC05"]
trace = "Req12"

[Req23]
description = "If the ontology contains syntactical errors, then Coua shall refuse to evaluate the ontology and produce a meaningful error message."
owner = "DLR"
level = "non-functional"
use-cases = ["UC06"]
trace = "Req50"

[Req24]
description = "If an artifact contains syntactical errors, then Coua shall refuse to produce a certification report that includes it and issue a meaningful error message."
owner = "DLR"
level = "non-functional"
trace = "Req01"
use-cases = ["UC04"]

[Req25]
description = "Coua shall allow for importing requirements data in a Comma Separated Values (CSV) format."
owner = "DLR"
level = "functional"
trace = "Req01"
use-cases = ["UC04"]

[Req26]
description = "Coua shall specify the format for requirements data."
owner = "DLR"
level = "functional"
trace = "Req01"
use-cases = ["UC08"]

[Req27]
description = "Coua shall allow for defining custom content in the certification report."
owner = "DLR"
level = "functional"
trace = "Req12"
use-cases = ["UC04"]

[Req28]
description = "Coua shall allow a project to run custom queries on the ontologies."
owner = "DLR"
level = "functional"
trace = "Req50"
use-cases = ["UC01"]

[Req29]
description = "Coua shall provide a well-defined output schema for the certification report."
owner = "DLR"
level = "functional"
trace = "Req12"
use-cases = ["UC09"]

[Req30]
description = "The project using Coua shall track all changes in an SCM."
owner = "DLR"
level = "non-functional"
trace = "Req01"
use-cases = ["UC05"]

[Req31]
description = "When a new version of the component is released, the artifact archive shall version and permanently record all software, configuration and non-reproducible artifacts that are required for recreating the certification report for that version."
owner = "DLR"
level = "functional"
use-cases = ["UC03"]
trace = "Req01"

[Req32]
description = "The ontologies shall model all necessary knowledge from the documents that specify what is required for certification approval."
owner = "DLR"
level = "functional"
trace = "Req50"
use-cases = ["UC06"]

[Req33]
description = "Coua shall be able to ingest ontologies in the OWL2 format."
owner = "DLR"
level = "functional"
trace = "Req50"
use-cases = ["UC04"]

[Req34]
description = "The certification report shall clearly display which objective is satisfied."
owner = "DLR"
level = "functional"
use-cases = ["UC01"]
trace = "Req12"

[Req35]
description = "If the certification report indicates that all objectives are met, Coua shall make it clear that this is not guaranteed."
owner = "DLR"
level = "functional"
use-cases = ["UC01"]
trace = "Req12"

[Req36]
description = "The certification report shall clearly display whether an objective has regressed."
owner = "DLR"
level = "functional"
use-cases = ["UC02"]
trace = "Req12"

[Req37]
description = "The certification report shall mark failing satisfiable objectives."
owner = "DLR"
level = "functional"
use-cases = ["UC10"]
trace = "Req12"

[Req38]
description = "The certification report shall mark not yet satisfiable objectives."
owner = "DLR"
level = "functional"
use-cases = ["UC10"]
trace = "Req12"

[Req39]
description = "When an objective is violated, the certification report shall highlight the precise artifacts that are the source of the violation."
owner = "DLR"
level = "functional"
use-cases = ["UC07"]
trace = "Req12"

[Req40]
description = "The certification report shall be human-readable."
owner = "DLR"
level = "functional"
use-cases = ["UC01"]
trace = "Req12"

[Req41]
description = "The certification report shall be machine-readable."
owner = "DLR"
level = "functional"
use-cases = ["UC09"]
trace = "Req12"

[Req42]
description = "The certification reports shall have the same contents in both human- and machine- readable forms."
owner = "DLR"
level = "functional"
use-cases = ["UC09"]
trace = "Req12"

[Req43]
description = "The certification report shall include all failed objectives."
owner = "DLR"
level = "functional"
trace = "Req12"

[Req44]
description = "The certification report shall present unsatisfiable objectives less prominently."
owner = "DLR"
level = "functional"
use-cases = ["UC10"]
trace = "Req12"

[Req45]
description = "While the artifacts provide the required information, the certification report shall include all data items and evidences required to build an assurance case."
owner = "DLR"
level = "functional"
trace = "Req12"
use-cases = ["UC10"]

[Req46]
description = "The certification framework shall allow for defining custom content in the rendered certification report."
owner = "DLR"
level = "functional"
trace = "Req12"
use-cases = ["UC10"]

[Req47]
description = "Coua shall finish producing the report in a time that allows for fast feedback during development."
owner = "DLR"
level = "non-functional"
trace = "Req12"
use-cases = ["UC02"]

[Req48]
description = "Coua shall use not more than half of the memory that is available in the CI or in the development requirement."
owner = "DLR"
level = "non-functional"
trace = "Req12"
use-cases = ["UC02"]

[Req50]
description = "Coua shall validate if the objectives for certification of the project are satisfied"
owner = "DLR"
level = "system"
use-cases = ["UC01"]
