# High-level requirements are developed.

PREFIX do178c: <https://gitlab.dlr.de/ft-ssy-avs/ap/coua/ontologies/do178c#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

ASK {
	FILTER EXISTS {
		SELECT ?ReqHigh
		WHERE
		{
			?reqHighClass rdfs:subClassOf+ do178c:HighLevelRequirement .
			?ReqHigh a ?reqHighClass .
		}
	}
}
