# Low-level requirements are developed.

PREFIX do178c: <https://gitlab.dlr.de/ft-ssy-avs/ap/coua/ontologies/do178c#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

ASK {
	FILTER EXISTS {
		SELECT ?ReqLow
		WHERE
		{
			?reqLowClass rdfs:subClassOf+ do178c:LowLevelRequirement .
			?ReqLow a ?reqLowClass .
		}
	}
}
