PREFIX do178c: <https://gitlab.dlr.de/ft-ssy-avs/ap/coua/ontologies/do178c#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?Requirement ?TestCase
WHERE
{
  ?reqClass rdfs:subClassOf do178c:Requirement .
  ?reqIdProp rdfs:subPropertyOf do178c:requirementId .

  ?req a ?reqClass ;
    ?reqIdProp ?Requirement .

  ?tcClass rdfs:subClassOf do178c:TestCase .
  ?coversProp rdfs:subPropertyOf do178c:covers .

  ?TestCase a ?tcClass ;
    # We match up the the requirment IDs here
    # Would be better to use do178c:covers, but missing classification of requirment IDs in mapping files to requirmeent IRIs ...
    ?coversProp ?Requirement .
}
ORDER BY ?Requirement
