PREFIX do178c: <https://gitlab.dlr.de/ft-ssy-avs/ap/coua/ontologies/do178c#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?Requirement ?Description ?Rationale ?Trace
WHERE
{
  ?reqclass rdfs:subClassOf+ do178c:Requirement .
  ?req a ?reqclass .

  ?requirementId rdfs:subPropertyOf+ do178c:requirementId .
  ?req ?requirementId ?Requirement .

  OPTIONAL {
    ?description rdfs:subPropertyOf+ do178c:requirementDescription .
    ?req ?description ?Description .
  }

  OPTIONAL {
    ?rationale rdfs:subPropertyOf+ do178c:requirementRationale .
    ?req ?rationale ?Rationale .
  }
  OPTIONAL {
    ?traces rdfs:subPropertyOf+ do178c:traces .
    ?requirementId rdfs:subPropertyOf+ do178c:requirementId .
    ?req ?traces ?tr.
    ?tr ?requirementId ?Trace .
   }
}
ORDER BY ?Requirement
