PREFIX do178c: <https://gitlab.dlr.de/ft-ssy-avs/ap/coua/ontologies/do178c#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?Requirement ?Location
WHERE
{
  ?reqClass rdfs:subClassOf do178c:Requirement .
  ?reqIdProp rdfs:subPropertyOf do178c:requirementId .
  ?req a ?reqClass ;
    ?reqIdProp ?Requirement .

  ?locationClass rdfs:subClassOf do178c:Location .
  ?Location a ?locationClass .

  ?traceClass rdfs:subClassOf do178c:TraceData .
  ?traceProp rdfs:subPropertyOf do178c:traces .
  ?traceReqIdProp rdfs:subPropertyOf do178c:requirementId .
  ?trace a ?traceClass ;
    ?traceProp ?Location ;
    ?traceReqIdProp ?Requirement .
}
ORDER BY ?Requirement
