PREFIX coua: <https://gitlab.dlr.de/ft-ssy-avs/ap/coua/schema#>

SELECT ?UC ?Req
WHERE
{
	?r coua:useCase ?u ;
		a coua:Requirement ;
		coua:requirementId ?Req .
	?u a coua:UseCase ;
		coua:ucId ?UC .
}
ORDER BY ?UC
