[profile.ci.junit]
# Generate a junit.xml test report for GitLab
path = "junit.xml"
# Print out output for failing tests as soon as they fail, and also at the end
# of the run (for easy scrollability).
failure-output = "immediate-final"
# Do not cancel the test run on the first failure.
fail-fast = false
