PREFIX coua: <https://gitlab.dlr.de/ft-ssy-avs/ap/coua/schema#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?Check ?Status ?Description
WHERE
{
  {
    ?checkC rdfs:subClassOf+ coua:Check .
    ?check a ?checkC .
  } UNION {
    ?check a coua:Check
  } .

  OPTIONAL {
    ?check coua:status ?status .
  }
  OPTIONAL {
    ?check coua:checkDisabled ?disabled
  }
  BIND(
    IF(bound(?disabled),
      "disabled",
      IF(?status = "true",
        "passed",
        "failed")) AS ?Status)

  ?check rdfs:label ?Check .
  ?check rdfs:comment ?Description .
}
ORDER BY ?Check
