PREFIX coua: <https://gitlab.dlr.de/ft-ssy-avs/ap/coua/schema#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?Check ?Status
WHERE
{
  ?check a coua:Check ;
    coua:status ?Status ;
    coua:checkName ?Check .
}
ORDER BY ?Check
