id = 10
title = "Incremental Certification"
actor = "Developer"
affects = [2.2, 2.3]
goal = "DLR-SMART10"
scope = "Certification Report"
level = "User"
story = "As a developer, during development, I want to be able to mark objectives which have not yet been worked on as not achievable, so that I can focus on the progress of the objective(s) I am working on."
stakeholders = ["Vendor", "Developer", "Reviewer"]
pre = ["The list of objectives for a project is known."]
trigger = "An objective that is currently not completed, but is planned to be completed in the future."
flow = ["The developer marks the objective as not achievable using the manifest file."]
post = ["The certification framework reports the failures of objectives, but the failures of marked objectives are featured less prominently."]
extensions = ["As a developer, I want to remove the marker from the objective I am working on so that I am notified of regressions."]
