id = 9
title = "Machine-Readable Certification Report"
actor = "Developer"
goal = "DLR-SMART2"
scope = "Certification Report"
affects = [2.2, 2.3, 4.1]
level = "User"
story = "As a developer I want the certification report to be machine-readable so that it be processed by additional tools."
stakeholders = ["Developer"]
pre = ["The certification report is generated in a standardized format."]
trigger = "The certification report is created."
flow = ["The certification report data is created and serialized in the standardized format."]
post = ["The report data is displayed by the COTS tools."]
extensions = ["As the vendor, I want to archive the report data to make historical data of my product searchable."]
