id = 4
title = "Use COTS Tools"
actor = "Developer"
goal = "DLR-SMART3"
affects = [2.2, 2.3, 4.1]
scope = "TDF"
level = "User"
story = "As a developer I want to use artifacts provided by my existing tooling as inputs for the certification framework so that I can check my certification progress."
stakeholders = ["Developer", "Reviewer"]
pre = ["The certification framework provides a means for describing how artifacts are created by custom tools.", "The certification framework provides ingestion methods for some pre-defined artifact types."]
trigger = "An output of a COTS tool is to be used as an input for the certification framework."
flow = ["The developer defines which artifact type the artifact has using the ADF and the tool which creates the artifact type using the TDF."]
post = ["The definitions are used by the certification framework to discover or create the artifacts and ingest them."]
extensions = ["As a developer, I want the certification framework to provide default definitions for some tools, so that I don't have to provide my own."]
