id = 8
title = "Tracing"
actor = "Software Developer"
goal = "DLR-SMART3"
affects = [2.2, 2.3]
scope = "ADF"
level = "User"
story = "As a developer I want to track the contents of artifacts like requirements, test cases, source code and object code onto each other so that I can use the tracing as a data-item."
stakeholders = ["Developer", "Reviewer"]
pre = ["The artifact types that should be traced are modeled using the ADF."]
trigger = "A new artifact is added."
flow = ["The developer uses an existing class defintion or creates a new class definition for the ADF inside an ontology.", "The developer declares that a specific artifact is of that type.", "The certification framework understands the defition and can use the contents of the artifacts for tracing."]
post = ["The report shows the tracing between the artifacts."]
extensions = ["As the certification authority I want to inspect the report to verify that sufficient coverage of requirements, source and object code exists."]
