name: Checks

on:
  pull_request:
  push:
    branches: [main]

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        command:
          - nix fmt -- --fail-on-change --no-cache
          - nix develop --command cog check
          - ./ci/rust-tests.sh
          - ./ci/rust-coverage.sh
          - nix build .#coua-cert && nix develop -c cp -rL result report
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v26
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-${{ github.job }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Run check ${{ matrix.check }}
        run: ${{ matrix.command }}
